// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qhtkejmmjupgmfotrewt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFodGtlam1tanVwZ21mb3RyZXd0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNTk2NzAsImV4cCI6MjA2MzkzNTY3MH0.9jrbGsagIy8X4CAprRcHj4qdcXpSMGn0VkMAVe4-vyE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);